name: Upload Python Package

on:
  push:
    paths:
      - openapi.yaml

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: "3.x"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade build
          python -m pip install --upgrade twine
          python -m pip install --upgrade PyYAML
      - name: Generate API
        run: |
          sh generate-openapi.sh
          sudo chown -R runner:docker openapi
      - name: Build and publish
        run: |
          python -m build ./openapi --outdir ./build
          python -m twine upload --repository-url https://test.pypi.org/legacy/ -p ${{ secrets.PYPI_TOKEN }} -u __token__ ./build/*
